language: cpp

env:
  global:
    - POCO_WEBSERVICE_ENVIRONMENT=build

os: linux

dist: trusty
sudo: enabled

cache:
  - apt

services:
  - mysql
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - libmysqlclient-dev
      - gcc-snapshot
      - gcc-6
      - g++-6

notifications:
    email:
      on_success: never  # default: change
      on_failure: always # default: always

before_install:
  # It sets GCC 6 as the default version.
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

install:
  # It makes available CMake 3.7.2
  - cd $HOME
  - wget https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz
  - tar -xf cmake-3.7.2.tar.gz
  - cd cmake-3.7.2
  - ./configure
  - make && sudo make install

  # It makes available Google Test
  - sudo sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib

  # It makes available Poco 1.8.1
  - cd $HOME
  - wget https://pocoproject.org/releases/poco-1.8.1/poco-1.8.1-all.tar.gz
  - tar -xf poco-1.8.1-all.tar.gz
  - cd poco-1.8.1-all
  - ./configure --no-tests --no-samples --everything --omit=MongoDB,Data/ODBC,Data/SQLite,PDF,CppParser,Crypto,NetSSL_OpenSSL,CppUnit,PageCompiler
  - make && sudo make install

before_script:
  # =============================================================
  # It makes available a MySQL User with proper privileges to
  # perform database related tests.
  # =============================================================
  - mysql -e "CREATE USER 'ci_environment'@'localhost' IDENTIFIED BY 'abc12345'; GRANT ALL ON *.* TO 'ci_environment'@'localhost'";

  # =============================================================
  # It removes standard Ant Jsch package for using the local one.
  # If both are kept Ant gets a bit confused and the build fails.
  # =============================================================
  - if [ -e "/usr/share/ant/lib/ant-jsch.jar" ]; then
      sudo rm "/usr/share/ant/lib/ant-jsch.jar"; fi

  # =============================================================
  # The following Ant Tasks:
  #  1. Create the database
  #  2. Create DBDeploy and Application tables as well as load
  #  sample data.
  # =============================================================
  - cd $TRAVIS_BUILD_DIR
  - ant -propertyfile ci.properties create_schema
  - ant -propertyfile ci.properties init_schema

  # It makes local libs path available in the PATH environmental variable.
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

script:
  # It creates a separated CMake build directory for building the application.
  - cd $HOME && sudo mkdir cmake-build && cd cmake-build
  # It enables all parts of the application for building.
  - sudo cmake $TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=yes -DENABLE_STANDALONE_SERVICE=yes
  # It compiles the application and run the tests.
  - sudo cmake --build . --target all -- -j 2
  - cd $TRAVIS_BUILD_DIR/bin && ./tests --gtest_filter=* --gtest_color=yes

after_script:
  # =============================================================
  # The following Ant Task destroys database and all sample data.
  # =============================================================
  - cd $TRAVIS_BUILD_DIR
  - ant -propertyfile ci.properties drop_schema

before_deploy:
 - cd $TRAVIS_BUILD_DIR
 - docker build -t poco-restful-webservice .

# deploy:
#  provider: gae
#  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
#  project: "poco-restful-webservice"
